name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  dart_mappable: ^4.7.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.13.1
  dart_mappable_builder: ^4.7.0
  lints: ^6.0.0
  test: ^1.25.6
